on:
  push:
    branches: [main]

  workflow_dispatch:
  
env:
  CODEQL_RESULTS_PATH: /results/go.sarif
  go-version: 'stable'
  terraform-tflint-version: 'v0.44.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Get dependencies
        run: |
          go mod download
          go mod tidy
      - name: Build
        run: go build

      - name: Test
        run: go test ./...

      - name: Upload CodeQL results
        uses: actions/upload-artifact@v3
        with:
          name: codeql-results
          path: ${{ github.workspace }}/${{ env.CODEQL_RESULTS_PATH }}

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          skip_check: CKV2_GHA_1
          
      - name: Terraform
        run: |
          terraform init
          terraform validate
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: ${{ env.terraform-tflint-version }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.vs1 }}

      - name: Helm lint
        run: helm lint .
