name: My Pipeline
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2	
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build			
      - name: Static Code Analysis and Security
        uses: github/codeql-action/analyze@v2	
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
      - name: go test
        run: go test -v ./...
      - name: Terraform
        run: |
          terraform validate
          tflint
          tfsec
      - name: Helm lint
        run: helm lint .
      - name: Package Helm chart
        run: helm package .
