name: My Pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
#         with:
#           github-token: ${{ secrets.vs }}
#           permissions: security-events.write, repository.read
          
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          skip_check: CKV2_GHA_1
          
      - name: Initialize Go module
        run: go mod init github.com/ViktorijaEl/new-m
      - name: Install dependencies
        run: go get -v -t -d ./...
      - name: Run tests
        run: go test -v ./...
        
      - name: Terraform
        run: |
          terraform init
          terraform validate
      - name: Install tflint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.30.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
      - name: Lint Terraform code
        run: |
          tflint --version
          tflint terraform/
          tfsec --version
          tfsec terraform/
          
      - name: Helm lint
        run: helm lint .
      - name: Package Helm chart
        run: helm package .
