name: My Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run tests
        run: go test -v ./...

      - name: Terraform
        run: |
          terraform init
          terraform validate

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.44.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: 'github/codeql'
          ref: 'main'
          path: 'codeql'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          sarif_file: codeql-results/go.sarif

      - name: Upload CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: codeql-results/go.sarif

      - name: Helm lint
        run: helm lint .
