name: My Pipeline

on:
  push:
    branches: [main]

env:
  CODEQL_RESULTS_PATH: /home/runner/work/new-m/results/go.sarif

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      security-events: write

    inputs:
      checkov-directory:
        required: true
        type: string
      checkov-framework:
        required: true
        type: string
      terraform-version:
        required: true
        type: string
      terraform-work-dir:
        required: true
        type: string
      terraform-tflint-version:
        required: true
        type: string
      generic-build-script:
        required: false
        type: string
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          
      - name: Get dependencies
        run: |
          go mod download
          go mod tidy
      - name: Build
        run: go build

      - name: Test
        run: go test ./...     
        
#       - name: Download dependencies
#         run: go mod download

#       - name: Run tests
#         run: go test ./...
          
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Upload CodeQL results
        uses: actions/upload-artifact@v3
        with:
          name: codeql-results
          path: ${{ env.CODEQL_RESULTS_PATH }}
      
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          skip_check: CKV2_GHA_1
#         with:
#           github_token: ${{ secrets.github-token }}      
   
      - name: Terraform
        run: |
          terraform init
          terraform validate
          
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: ${{ inputs.terraform-tflint-version }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
      
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.github-token }}
          
      - name: Helm lint
        run: helm lint .
