name: My Pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
#         with:
#           github-token: ${{ secrets.vs }}
#           permissions: security-events.write, repository.read
          
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
      - name: go test
        run: go test -v ./...
      - name: Terraform
        run: |
          terraform validate
          tflint
          tfsec
      - name: Helm lint
        run: helm lint .
      - name: Package Helm chart
        run: helm package .
