name: My Pipeline
on:
  push:
    branches: [main]
#   pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
          
      - name: Initialize Go module
        run: go mod init github.com/ViktorijaEl/new-m

      - name: Build
        run: go build

      - name: Static Code Analysis and Security
        uses: github/codeql-action/analyze@v2
        with:
          token: ${{ secrets.vs }}
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
      - name: go test
        run: go test -v ./...
      - name: Terraform
        run: |
          terraform validate
          tflint
          tfsec
      - name: Helm lint
        run: helm lint .
      - name: Package Helm chart
        run: helm package .
