on:
  push:
    branches: [main]
  workflow_dispatch:
    permissions:
      contents: read
      security-events: write
      actions: read

env:
  CODEQL_RESULTS_PATH: ${{ github.workspace }}
  go-version: 'stable'
  terraform-tflint-version: 'v0.44.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Get dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build
        run: go build

      - name: Test
        run: go test ./...

  scan:
    needs: build
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          # Path to the CodeQL queries to use (required)
          queries: ./codeql-go-repository-scanner

      - name: Upload CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: ${{ env.CODEQL_RESULTS_PATH }}

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v2
        with:
          directory: "."
          skip_check: CKV2_GHA_1

      - name: Terraform
        run: |
          terraform init
          terraform validate

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: ${{ env.terraform-tflint-version }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.vs1 }}

      - name: Helm lint
        run: helm lint .
