name: My Pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
#     security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:     
          token: ${{ secrets.vs }}

      - name: Checkout bridgecrewio/checkov-action
        uses: actions/checkout@v2
        with:
          repository: bridgecrewio/checkov-action
          ref: master
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master

      - name: go test
        run: go test -v ./...
      - name: Terraform
        run: |
          terraform validate
          tflint
          tfsec
      - name: Helm lint
        run: helm lint .
      - name: Package Helm chart
        run: helm package .
