name: manual-approval

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to terraform directory
        run: |
          pwd
          cd terraform
          pwd

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: cd terraform && terraform apply ../plan.tfplan

  approval:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Manual Approval
        id: approval
        uses: peter-evans/manual-approval@v2
        with:
          comment: Please review and approve this Terraform plan
