name: Manual Approval

on:
  workflow_run:
    workflows: [Workflow 1]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=plan.tfplan

  approval:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Manual Approval
        id: approval
        uses: peter-evans/manual-approval@v2
        with:
          comment: Please review and approve this Terraform plan
