name: manual-approval
permissions:
  contents: read
  actions: read
  security-events: write

on:
  repository_dispatch:
      inputs: 
      actions_template_v1:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'actions_template_v1'
        types:
          - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -out=plan.tfplan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: plan.tfplan
  approval:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Manual Approval
        id: approval
        uses: peter-evans/manual-approval@v2
        with:
          comment: Please review and approve this Terraform plan
      - name: Terraform Apply
        if: steps.approval.outputs.approved == 'true'
        run: terraform apply plan.tfplan
